import { Car } from '../models/car.model';

export const MOCK_CARS: Car[] = [
  {
    id: '1',
    brand: 'Maruti Suzuki',
    model: 'Swift',
    year: 2022,
    price: 650000,
    mileage: '23.2 kmpl',
    fuelType: 'Petrol',
    transmission: 'Manual',
    bodyType: 'Hatchback',
    color: 'Red',
    owners: 1,
    location: 'Mumbai',
    images: [
      'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800'
    ],
    features: ['ABS', 'Airbags', 'Power Steering', 'AC', 'Touchscreen Infotainment'],
    description: 'Well maintained Maruti Suzuki Swift in excellent condition. First owner with complete service history.',
    dealerId: 'd1',
    dealerName: 'Premium Motors',
    registrationYear: 2022,
    insuranceValidity: 'Dec 2025',
    kmDriven: 15000,
    rating: 4.5,
    isFeatured: true,
    isNew: false,
    engineCapacity: '1197 cc',
    seatingCapacity: 5,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15')
  },
  {
    id: '2',
    brand: 'Hyundai',
    model: 'Creta',
    year: 2023,
    price: 1450000,
    mileage: '17.4 kmpl',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'SUV',
    color: 'White',
    owners: 1,
    location: 'Delhi',
    images: [
      'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800',
      'https://images.unsplash.com/photo-1581540222194-0def2dda95b8?w=800'
    ],
    features: ['Sunroof', 'Cruise Control', 'Leather Seats', 'Android Auto', 'Rear Camera'],
    description: 'Brand new condition Hyundai Creta with all modern features. Hardly driven.',
    dealerId: 'd2',
    dealerName: 'City Auto Sales',
    registrationYear: 2023,
    insuranceValidity: 'Mar 2026',
    kmDriven: 8000,
    rating: 4.8,
    isFeatured: true,
    isNew: false,
    engineCapacity: '1493 cc',
    seatingCapacity: 5,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10')
  },
  {
    id: '3',
    brand: 'Tata',
    model: 'Nexon EV',
    year: 2024,
    price: 1799000,
    mileage: '312 km/charge',
    fuelType: 'Electric',
    transmission: 'Automatic',
    bodyType: 'SUV',
    color: 'Blue',
    owners: 1,
    location: 'Bangalore',
    images: [
      'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800',
      'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800'
    ],
    features: ['Fast Charging', 'Connected Car Tech', 'Air Purifier', 'Digital Cluster', 'Wireless Charging'],
    description: 'Latest Tata Nexon EV with maximum range. Perfect electric SUV for city driving.',
    dealerId: 'd3',
    dealerName: 'EV Motors Hub',
    registrationYear: 2024,
    insuranceValidity: 'Jan 2027',
    kmDriven: 2500,
    rating: 4.9,
    isFeatured: true,
    isNew: true,
    engineCapacity: 'Electric Motor',
    seatingCapacity: 5,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20')
  },
  {
    id: '4',
    brand: 'Honda',
    model: 'City',
    year: 2021,
    price: 980000,
    mileage: '18.5 kmpl',
    fuelType: 'Petrol',
    transmission: 'Manual',
    bodyType: 'Sedan',
    color: 'Silver',
    owners: 1,
    location: 'Pune',
    images: [
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800',
      'https://images.unsplash.com/photo-1619405399517-d7fce0f13302?w=800'
    ],
    features: ['Keyless Entry', 'Push Button Start', 'Rear AC Vents', 'Alloy Wheels', 'LED DRL'],
    description: 'Honda City in pristine condition. Single owner, all services done at authorized center.',
    dealerId: 'd1',
    dealerName: 'Premium Motors',
    registrationYear: 2021,
    insuranceValidity: 'Aug 2025',
    kmDriven: 28000,
    rating: 4.3,
    isFeatured: false,
    isNew: false,
    engineCapacity: '1498 cc',
    seatingCapacity: 5,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05')
  },
  {
    id: '5',
    brand: 'Mahindra',
    model: 'XUV700',
    year: 2023,
    price: 2100000,
    mileage: '14.5 kmpl',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'SUV',
    color: 'Black',
    owners: 1,
    location: 'Chennai',
    images: [
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800'
    ],
    features: ['ADAS', 'Panoramic Sunroof', 'Sony Audio', '360 Camera', 'Ventilated Seats'],
    description: 'Top-of-the-line Mahindra XUV700 with all advanced features. Like new condition.',
    dealerId: 'd4',
    dealerName: 'Luxury Car Point',
    registrationYear: 2023,
    insuranceValidity: 'May 2026',
    kmDriven: 12000,
    rating: 4.7,
    isFeatured: true,
    isNew: false,
    engineCapacity: '2184 cc',
    seatingCapacity: 7,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01')
  },
  {
    id: '6',
    brand: 'Toyota',
    model: 'Fortuner',
    year: 2022,
    price: 3800000,
    mileage: '11.5 kmpl',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'SUV',
    color: 'White',
    owners: 1,
    location: 'Hyderabad',
    images: [
      'https://images.unsplash.com/photo-1581540222194-0def2dda95b8?w=800',
      'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800'
    ],
    features: ['4WD', 'Hill Assist', 'JBL Audio', 'Electric Tailgate', 'Multi-terrain Select'],
    description: 'Premium Toyota Fortuner in excellent condition. All services from Toyota.',
    dealerId: 'd4',
    dealerName: 'Luxury Car Point',
    registrationYear: 2022,
    insuranceValidity: 'Nov 2025',
    kmDriven: 22000,
    rating: 4.8,
    isFeatured: true,
    isNew: false,
    engineCapacity: '2755 cc',
    seatingCapacity: 7,
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25')
  },
  {
    id: '7',
    brand: 'Kia',
    model: 'Seltos',
    year: 2023,
    price: 1680000,
    mileage: '16.8 kmpl',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'SUV',
    color: 'Grey',
    owners: 1,
    location: 'Kolkata',
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
      'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800'
    ],
    features: ['Connected App', 'Air Purifier', 'Wireless Charging', 'Sound Mood Lighting', 'TPMS'],
    description: 'Kia Seltos GTX with top variant features. Very well maintained.',
    dealerId: 'd2',
    dealerName: 'City Auto Sales',
    registrationYear: 2023,
    insuranceValidity: 'Jul 2026',
    kmDriven: 9500,
    rating: 4.6,
    isFeatured: false,
    isNew: false,
    engineCapacity: '1497 cc',
    seatingCapacity: 5,
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05')
  },
  {
    id: '8',
    brand: 'Volkswagen',
    model: 'Virtus',
    year: 2024,
    price: 1450000,
    mileage: '18.2 kmpl',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    color: 'Red',
    owners: 1,
    location: 'Ahmedabad',
    images: [
      'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800',
      'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800'
    ],
    features: ['Digital Cockpit', 'Cruise Control', 'Rain Sensing Wipers', 'Auto Headlamps', 'Paddle Shifters'],
    description: 'Brand new Volkswagen Virtus with premium German engineering.',
    dealerId: 'd5',
    dealerName: 'Euro Cars Gallery',
    registrationYear: 2024,
    insuranceValidity: 'Feb 2027',
    kmDriven: 1200,
    rating: 4.7,
    isFeatured: true,
    isNew: true,
    engineCapacity: '1498 cc',
    seatingCapacity: 5,
    createdAt: new Date('2024-02-12'),
    updatedAt: new Date('2024-02-12')
  },
  {
    id: '9',
    brand: 'MG',
    model: 'Hector',
    year: 2022,
    price: 1650000,
    mileage: '15.2 kmpl',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    bodyType: 'SUV',
    color: 'Bronze',
    owners: 1,
    location: 'Jaipur',
    images: [
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800'
    ],
    features: ['Panoramic Sunroof', 'i-SMART Technology', 'Voice Commands', '10.4" Touchscreen', 'Air Quality Monitor'],
    description: 'MG Hector with hybrid technology for better fuel efficiency. Excellent condition.',
    dealerId: 'd3',
    dealerName: 'EV Motors Hub',
    registrationYear: 2022,
    insuranceValidity: 'Sep 2025',
    kmDriven: 18000,
    rating: 4.4,
    isFeatured: false,
    isNew: false,
    engineCapacity: '1451 cc + Electric Motor',
    seatingCapacity: 5,
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-18')
  },
  {
    id: '10',
    brand: 'Skoda',
    model: 'Kushaq',
    year: 2023,
    price: 1580000,
    mileage: '17.8 kmpl',
    fuelType: 'Petrol',
    transmission: 'Manual',
    bodyType: 'SUV',
    color: 'Silver',
    owners: 1,
    location: 'Surat',
    images: [
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800',
      'https://images.unsplash.com/photo-1619405399517-d7fce0f13302?w=800'
    ],
    features: ['Virtual Cockpit', 'Ventilated Front Seats', 'Auto Climate Control', 'Wireless CarPlay', 'ESP'],
    description: 'Skoda Kushaq Style variant with all premium features. Very low mileage.',
    dealerId: 'd5',
    dealerName: 'Euro Cars Gallery',
    registrationYear: 2023,
    insuranceValidity: 'Apr 2026',
    kmDriven: 7800,
    rating: 4.5,
    isFeatured: false,
    isNew: false,
    engineCapacity: '1498 cc',
    seatingCapacity: 5,
    createdAt: new Date('2024-02-08'),
    updatedAt: new Date('2024-02-08')
  }
];
