import { Car } from '../models/car.model';

// ── Image pool (by body-type category) ────────────────────────────────────────
const IMG = {
  hatch: [
    'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=640&q=80',
    'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=640&q=80',
    'https://images.unsplash.com/photo-1574023278028-76cf6e55dfbd?w=640&q=80',
  ],
  sedan: [
    'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=640&q=80',
    'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=640&q=80',
    'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=640&q=80',
  ],
  suv: [
    'https://images.unsplash.com/photo-1568844293986-8d0400bd4745?w=640&q=80',
    'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=640&q=80',
    'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=640&q=80',
    'https://images.unsplash.com/photo-1581540222194-0def2dda95b8?w=640&q=80',
    'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=640&q=80',
  ],
  electric: [
    'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=640&q=80',
    'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=640&q=80',
    'https://images.unsplash.com/photo-1571987502227-9231b837d92a?w=640&q=80',
  ],
  luxury: [
    'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=640&q=80',
    'https://images.unsplash.com/photo-1503736334956-4c8f8e4dc1d0?w=640&q=80',
    'https://images.unsplash.com/photo-1622119614-baf08c40ecef?w=640&q=80',
  ],
};

function img(type: keyof typeof IMG, idx = 0): string[] {
  const arr = IMG[type];
  return [arr[idx % arr.length], arr[(idx + 1) % arr.length]];
}

export const MOCK_CARS: Car[] = [
  // ── 1-10: Original cars ──────────────────────────────────────────────────
  {
    id: '1', brand: 'Maruti Suzuki', model: 'Swift', year: 2022, price: 650000,
    mileage: '23.2 kmpl', fuelType: 'Petrol', transmission: 'Manual',
    bodyType: 'Hatchback', color: 'Red', owners: 1, location: 'Mumbai',
    images: img('hatch', 0),
    features: ['ABS', 'Airbags', 'Power Steering', 'AC', 'Touchscreen'],
    description: 'Well maintained Maruti Suzuki Swift in excellent condition.',
    dealerId: 'd1', dealerName: 'Premium Motors', registrationYear: 2022,
    insuranceValidity: 'Dec 2025', kmDriven: 15000, rating: 4.5,
    isFeatured: true, isNew: false, engineCapacity: '1197 cc', seatingCapacity: 5,
    createdAt: new Date('2024-01-15'), updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2', brand: 'Hyundai', model: 'Creta', year: 2023, price: 1450000,
    mileage: '17.4 kmpl', fuelType: 'Diesel', transmission: 'Automatic',
    bodyType: 'SUV', color: 'White', owners: 1, location: 'Delhi',
    images: img('suv', 0),
    features: ['Sunroof', 'Cruise Control', 'Leather Seats', 'Android Auto', 'Rear Camera'],
    description: 'Brand new condition Hyundai Creta with all modern features.',
    dealerId: 'd2', dealerName: 'City Auto Sales', registrationYear: 2023,
    insuranceValidity: 'Mar 2026', kmDriven: 8000, rating: 4.8,
    isFeatured: true, isNew: false, engineCapacity: '1493 cc', seatingCapacity: 5,
    createdAt: new Date('2024-02-10'), updatedAt: new Date('2024-02-10'),
  },
  {
    id: '3', brand: 'Tata', model: 'Nexon EV', year: 2024, price: 1799000,
    mileage: '312 km/charge', fuelType: 'Electric', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Blue', owners: 1, location: 'Bangalore',
    images: img('electric', 0),
    features: ['Fast Charging', 'Connected Car', 'Air Purifier', 'Digital Cluster'],
    description: 'Latest Tata Nexon EV with maximum range.',
    dealerId: 'd3', dealerName: 'EV Motors Hub', registrationYear: 2024,
    insuranceValidity: 'Jan 2027', kmDriven: 2500, rating: 4.9,
    isFeatured: true, isNew: true, engineCapacity: 'Electric Motor', seatingCapacity: 5,
    createdAt: new Date('2024-01-20'), updatedAt: new Date('2024-01-20'),
  },
  {
    id: '4', brand: 'Honda', model: 'City', year: 2021, price: 980000,
    mileage: '18.5 kmpl', fuelType: 'Petrol', transmission: 'Manual',
    bodyType: 'Sedan', color: 'Silver', owners: 1, location: 'Pune',
    images: img('sedan', 0),
    features: ['Keyless Entry', 'Push Button Start', 'Rear AC Vents', 'Alloy Wheels'],
    description: 'Honda City in pristine condition. Single owner.',
    dealerId: 'd1', dealerName: 'Premium Motors', registrationYear: 2021,
    insuranceValidity: 'Aug 2025', kmDriven: 28000, rating: 4.3,
    isFeatured: false, isNew: false, engineCapacity: '1498 cc', seatingCapacity: 5,
    createdAt: new Date('2024-01-05'), updatedAt: new Date('2024-01-05'),
  },
  {
    id: '5', brand: 'Mahindra', model: 'XUV700', year: 2023, price: 2100000,
    mileage: '14.5 kmpl', fuelType: 'Diesel', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Black', owners: 1, location: 'Chennai',
    images: img('suv', 1),
    features: ['ADAS', 'Panoramic Sunroof', 'Sony Audio', '360 Camera'],
    description: 'Top-of-the-line Mahindra XUV700 with all advanced features.',
    dealerId: 'd4', dealerName: 'Luxury Car Point', registrationYear: 2023,
    insuranceValidity: 'May 2026', kmDriven: 12000, rating: 4.7,
    isFeatured: true, isNew: false, engineCapacity: '2184 cc', seatingCapacity: 7,
    createdAt: new Date('2024-02-01'), updatedAt: new Date('2024-02-01'),
  },
  {
    id: '6', brand: 'Toyota', model: 'Fortuner', year: 2022, price: 3800000,
    mileage: '11.5 kmpl', fuelType: 'Diesel', transmission: 'Automatic',
    bodyType: 'SUV', color: 'White', owners: 1, location: 'Hyderabad',
    images: img('suv', 2),
    features: ['4WD', 'Hill Assist', 'JBL Audio', 'Electric Tailgate'],
    description: 'Premium Toyota Fortuner in excellent condition.',
    dealerId: 'd4', dealerName: 'Luxury Car Point', registrationYear: 2022,
    insuranceValidity: 'Nov 2025', kmDriven: 22000, rating: 4.8,
    isFeatured: true, isNew: false, engineCapacity: '2755 cc', seatingCapacity: 7,
    createdAt: new Date('2024-01-25'), updatedAt: new Date('2024-01-25'),
  },
  {
    id: '7', brand: 'Kia', model: 'Seltos', year: 2023, price: 1680000,
    mileage: '16.8 kmpl', fuelType: 'Petrol', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Grey', owners: 1, location: 'Kolkata',
    images: img('suv', 3),
    features: ['Connected App', 'Air Purifier', 'Wireless Charging', 'TPMS'],
    description: 'Kia Seltos GTX with top variant features.',
    dealerId: 'd2', dealerName: 'City Auto Sales', registrationYear: 2023,
    insuranceValidity: 'Jul 2026', kmDriven: 9500, rating: 4.6,
    isFeatured: false, isNew: false, engineCapacity: '1497 cc', seatingCapacity: 5,
    createdAt: new Date('2024-02-05'), updatedAt: new Date('2024-02-05'),
  },
  {
    id: '8', brand: 'Volkswagen', model: 'Virtus', year: 2024, price: 1450000,
    mileage: '18.2 kmpl', fuelType: 'Petrol', transmission: 'Automatic',
    bodyType: 'Sedan', color: 'Red', owners: 1, location: 'Ahmedabad',
    images: img('sedan', 1),
    features: ['Digital Cockpit', 'Cruise Control', 'Rain Sensing Wipers'],
    description: 'Brand new Volkswagen Virtus with premium German engineering.',
    dealerId: 'd5', dealerName: 'Euro Cars Gallery', registrationYear: 2024,
    insuranceValidity: 'Feb 2027', kmDriven: 1200, rating: 4.7,
    isFeatured: true, isNew: true, engineCapacity: '1498 cc', seatingCapacity: 5,
    createdAt: new Date('2024-02-12'), updatedAt: new Date('2024-02-12'),
  },
  {
    id: '9', brand: 'MG', model: 'Hector', year: 2022, price: 1650000,
    mileage: '15.2 kmpl', fuelType: 'Hybrid', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Bronze', owners: 1, location: 'Jaipur',
    images: img('suv', 4),
    features: ['Panoramic Sunroof', 'i-SMART Technology', '10.4" Touchscreen'],
    description: 'MG Hector with hybrid technology for better fuel efficiency.',
    dealerId: 'd3', dealerName: 'EV Motors Hub', registrationYear: 2022,
    insuranceValidity: 'Sep 2025', kmDriven: 18000, rating: 4.4,
    isFeatured: false, isNew: false, engineCapacity: '1451 cc + Motor', seatingCapacity: 5,
    createdAt: new Date('2024-01-18'), updatedAt: new Date('2024-01-18'),
  },
  {
    id: '10', brand: 'Skoda', model: 'Kushaq', year: 2023, price: 1580000,
    mileage: '17.8 kmpl', fuelType: 'Petrol', transmission: 'Manual',
    bodyType: 'SUV', color: 'Silver', owners: 1, location: 'Surat',
    images: img('sedan', 2),
    features: ['Virtual Cockpit', 'Ventilated Seats', 'Auto Climate Control'],
    description: 'Skoda Kushaq Style variant with all premium features.',
    dealerId: 'd5', dealerName: 'Euro Cars Gallery', registrationYear: 2023,
    insuranceValidity: 'Apr 2026', kmDriven: 7800, rating: 4.5,
    isFeatured: false, isNew: false, engineCapacity: '1498 cc', seatingCapacity: 5,
    createdAt: new Date('2024-02-08'), updatedAt: new Date('2024-02-08'),
  },

  // ── 11-20: Budget segment ₹3L–₹9L ────────────────────────────────────────
  {
    id: '11', brand: 'Maruti Suzuki', model: 'Dzire', year: 2022, price: 710000,
    mileage: '23.3 kmpl', fuelType: 'Petrol', transmission: 'Manual',
    bodyType: 'Sedan', color: 'Pearl White', owners: 1, location: 'Nagpur',
    images: img('sedan', 0),
    features: ['ABS', 'EBD', 'Rear Parking Sensors', 'Auto AC', 'Alloy Wheels'],
    description: 'Maruti Dzire ZXI with full safety features. Single owner.',
    dealerId: 'd1', dealerName: 'Premium Motors', registrationYear: 2022,
    insuranceValidity: 'Jan 2026', kmDriven: 22000, rating: 4.3,
    isFeatured: false, isNew: false, engineCapacity: '1197 cc', seatingCapacity: 5,
    createdAt: new Date('2024-01-10'), updatedAt: new Date('2024-01-10'),
  },
  {
    id: '12', brand: 'Hyundai', model: 'i20', year: 2023, price: 880000,
    mileage: '19.65 kmpl', fuelType: 'Petrol', transmission: 'Manual',
    bodyType: 'Hatchback', color: 'Titan Grey', owners: 1, location: 'Delhi',
    images: img('hatch', 1),
    features: ['10.25" Touchscreen', 'Wireless CarPlay', 'BlueLink Connected', 'Sunroof'],
    description: 'Hyundai i20 Asta with premium features in mint condition.',
    dealerId: 'd2', dealerName: 'City Auto Sales', registrationYear: 2023,
    insuranceValidity: 'Jun 2026', kmDriven: 11000, rating: 4.5,
    isFeatured: true, isNew: false, engineCapacity: '1197 cc', seatingCapacity: 5,
    createdAt: new Date('2024-01-22'), updatedAt: new Date('2024-01-22'),
  },
  {
    id: '13', brand: 'Tata', model: 'Altroz', year: 2023, price: 760000,
    mileage: '19.01 kmpl', fuelType: 'Petrol', transmission: 'Manual',
    bodyType: 'Hatchback', color: 'Magnetic Red', owners: 1, location: 'Pune',
    images: img('hatch', 2),
    features: ['TPMS', 'ABS', 'Rear Parking Sensor', 'Digital Cluster', 'Auto AC'],
    description: 'Tata Altroz XZ+ with best-in-class safety. Well maintained.',
    dealerId: 'd3', dealerName: 'EV Motors Hub', registrationYear: 2023,
    insuranceValidity: 'Mar 2026', kmDriven: 14000, rating: 4.2,
    isFeatured: false, isNew: false, engineCapacity: '1199 cc', seatingCapacity: 5,
    createdAt: new Date('2024-02-03'), updatedAt: new Date('2024-02-03'),
  },
  {
    id: '14', brand: 'Renault', model: 'Triber', year: 2022, price: 640000,
    mileage: '18.9 kmpl', fuelType: 'Petrol', transmission: 'Manual',
    bodyType: 'SUV', color: 'Cedar Brown', owners: 1, location: 'Jaipur',
    images: img('suv', 0),
    features: ['8" Touchscreen', 'EasyLink', 'Adjustable 3rd Row', 'ABS'],
    description: 'Renault Triber 7-seater in excellent condition. One owner.',
    dealerId: 'd1', dealerName: 'Premium Motors', registrationYear: 2022,
    insuranceValidity: 'Oct 2025', kmDriven: 38000, rating: 4.1,
    isFeatured: false, isNew: false, engineCapacity: '999 cc', seatingCapacity: 7,
    createdAt: new Date('2024-01-08'), updatedAt: new Date('2024-01-08'),
  },
  {
    id: '15', brand: 'Nissan', model: 'Magnite', year: 2023, price: 820000,
    mileage: '17.4 kmpl', fuelType: 'Petrol', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Blade Silver', owners: 1, location: 'Chennai',
    images: img('suv', 1),
    features: ['360 View Camera', 'Wireless Charging', 'Air Purifier', 'Sunroof'],
    description: 'Nissan Magnite Turbo CVT top variant. Like new condition.',
    dealerId: 'd2', dealerName: 'City Auto Sales', registrationYear: 2023,
    insuranceValidity: 'Aug 2026', kmDriven: 9800, rating: 4.4,
    isFeatured: false, isNew: false, engineCapacity: '999 cc Turbo', seatingCapacity: 5,
    createdAt: new Date('2024-01-30'), updatedAt: new Date('2024-01-30'),
  },
  {
    id: '16', brand: 'Maruti Suzuki', model: 'Alto K10', year: 2023, price: 460000,
    mileage: '24.39 kmpl', fuelType: 'Petrol', transmission: 'Manual',
    bodyType: 'Hatchback', color: 'Speedy Blue', owners: 1, location: 'Bhopal',
    images: img('hatch', 0),
    features: ['ABS', 'EBD', 'Reverse Parking Assist', 'Digital Instrument'],
    description: 'Maruti Alto K10 VXI+. Best entry level hatchback. Low mileage.',
    dealerId: 'd1', dealerName: 'Premium Motors', registrationYear: 2023,
    insuranceValidity: 'Feb 2026', kmDriven: 7500, rating: 4.0,
    isFeatured: false, isNew: false, engineCapacity: '998 cc', seatingCapacity: 5,
    createdAt: new Date('2024-02-15'), updatedAt: new Date('2024-02-15'),
  },
  {
    id: '17', brand: 'Hyundai', model: 'Grand i10 Nios', year: 2022, price: 590000,
    mileage: '20.7 kmpl', fuelType: 'Petrol', transmission: 'Manual',
    bodyType: 'Hatchback', color: 'Fiery Red', owners: 1, location: 'Kolkata',
    images: img('hatch', 1),
    features: ['Wireless Android Auto', 'Rear Camera', 'Cruise Control', 'Auto AC'],
    description: 'Hyundai Grand i10 Nios Sports in very good condition.',
    dealerId: 'd2', dealerName: 'City Auto Sales', registrationYear: 2022,
    insuranceValidity: 'Dec 2025', kmDriven: 24000, rating: 4.2,
    isFeatured: false, isNew: false, engineCapacity: '1197 cc', seatingCapacity: 5,
    createdAt: new Date('2024-01-12'), updatedAt: new Date('2024-01-12'),
  },
  {
    id: '18', brand: 'Tata', model: 'Punch', year: 2023, price: 790000,
    mileage: '18.97 kmpl', fuelType: 'Petrol', transmission: 'Manual',
    bodyType: 'SUV', color: 'Daytona Grey', owners: 1, location: 'Ahmedabad',
    images: img('suv', 2),
    features: ['iRA Connected', 'Sunroof', 'TPMS', 'Air Purifier', 'Walk-in Device'],
    description: 'Tata Punch Adventure S top trim. Very well maintained micro SUV.',
    dealerId: 'd3', dealerName: 'EV Motors Hub', registrationYear: 2023,
    insuranceValidity: 'May 2026', kmDriven: 10200, rating: 4.5,
    isFeatured: true, isNew: false, engineCapacity: '1199 cc', seatingCapacity: 5,
    createdAt: new Date('2024-01-28'), updatedAt: new Date('2024-01-28'),
  },
  {
    id: '19', brand: 'Honda', model: 'Amaze', year: 2023, price: 950000,
    mileage: '18.6 kmpl', fuelType: 'Petrol', transmission: 'Automatic',
    bodyType: 'Sedan', color: 'Meteoroid Grey', owners: 1, location: 'Noida',
    images: img('sedan', 1),
    features: ['CVT Gearbox', 'Lane Watch Camera', '7" Touchscreen', 'Walk-in Device'],
    description: 'Honda Amaze ZX CVT with lane watch technology. Single owner.',
    dealerId: 'd1', dealerName: 'Premium Motors', registrationYear: 2023,
    insuranceValidity: 'Jun 2026', kmDriven: 8500, rating: 4.3,
    isFeatured: false, isNew: false, engineCapacity: '1199 cc', seatingCapacity: 5,
    createdAt: new Date('2024-02-07'), updatedAt: new Date('2024-02-07'),
  },
  {
    id: '20', brand: 'Maruti Suzuki', model: 'Ertiga', year: 2022, price: 1080000,
    mileage: '20.3 kmpl', fuelType: 'CNG', transmission: 'Manual',
    bodyType: 'SUV', color: 'Oxford Blue', owners: 1, location: 'Indore',
    images: img('suv', 3),
    features: ['CNG Kit', 'Smart Hybrid', '7-Seater', 'Rear AC', 'Alloy Wheels'],
    description: 'Maruti Ertiga ZXI CNG. Excellent mileage. Family MPV in great condition.',
    dealerId: 'd1', dealerName: 'Premium Motors', registrationYear: 2022,
    insuranceValidity: 'Jan 2026', kmDriven: 31000, rating: 4.3,
    isFeatured: false, isNew: false, engineCapacity: '1462 cc CNG', seatingCapacity: 7,
    createdAt: new Date('2024-01-06'), updatedAt: new Date('2024-01-06'),
  },

  // ── 21-35: Mid segment ₹10L–₹25L ─────────────────────────────────────────
  {
    id: '21', brand: 'Maruti Suzuki', model: 'Grand Vitara', year: 2023, price: 1320000,
    mileage: '21.11 kmpl', fuelType: 'Hybrid', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Celestial Blue', owners: 1, location: 'Mumbai',
    images: img('suv', 0),
    features: ['AllGrip AWD', 'Hybrid Drive', 'Head-Up Display', 'Ventilated Seats'],
    description: 'Maruti Grand Vitara Alpha+ Hybrid AWD. Best in segment fuel economy.',
    dealerId: 'd1', dealerName: 'Premium Motors', registrationYear: 2023,
    insuranceValidity: 'Sep 2026', kmDriven: 6000, rating: 4.6,
    isFeatured: true, isNew: false, engineCapacity: '1490 cc Hybrid', seatingCapacity: 5,
    createdAt: new Date('2024-02-20'), updatedAt: new Date('2024-02-20'),
  },
  {
    id: '22', brand: 'Hyundai', model: 'Venue', year: 2023, price: 1050000,
    mileage: '17.5 kmpl', fuelType: 'Petrol', transmission: 'Manual',
    bodyType: 'SUV', color: 'Polar White', owners: 1, location: 'Delhi',
    images: img('suv', 1),
    features: ['BlueLink 60+ Features', 'Sunroof', 'Air Purifier', 'Wireless AA'],
    description: 'Hyundai Venue SX(O) top variant. Fully loaded connected SUV.',
    dealerId: 'd2', dealerName: 'City Auto Sales', registrationYear: 2023,
    insuranceValidity: 'Apr 2026', kmDriven: 14500, rating: 4.4,
    isFeatured: false, isNew: false, engineCapacity: '1197 cc Turbo', seatingCapacity: 5,
    createdAt: new Date('2024-01-17'), updatedAt: new Date('2024-01-17'),
  },
  {
    id: '23', brand: 'Kia', model: 'Sonet', year: 2023, price: 1290000,
    mileage: '18.3 kmpl', fuelType: 'Diesel', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Aurora Black', owners: 1, location: 'Bangalore',
    images: img('suv', 2),
    features: ['10.25" Touchscreen', 'Bose Sound', 'Ventilated Seats', 'Sunroof'],
    description: 'Kia Sonet HTX+ diesel AT. Premium compact SUV in top condition.',
    dealerId: 'd2', dealerName: 'City Auto Sales', registrationYear: 2023,
    insuranceValidity: 'Jul 2026', kmDriven: 11200, rating: 4.6,
    isFeatured: true, isNew: false, engineCapacity: '1493 cc', seatingCapacity: 5,
    createdAt: new Date('2024-02-02'), updatedAt: new Date('2024-02-02'),
  },
  {
    id: '24', brand: 'Toyota', model: 'Urban Cruiser Hyryder', year: 2024, price: 1540000,
    mileage: '21.1 kmpl', fuelType: 'Hybrid', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Cafe White', owners: 1, location: 'Chennai',
    images: img('suv', 3),
    features: ['Strong Hybrid', 'AWD', 'HUD', 'Panoramic View Monitor', 'Ventilated Seats'],
    description: 'Toyota Hyryder V Hybrid AWD. Near zero fuel costs with hybrid drive.',
    dealerId: 'd4', dealerName: 'Luxury Car Point', registrationYear: 2024,
    insuranceValidity: 'Jan 2027', kmDriven: 3200, rating: 4.7,
    isFeatured: true, isNew: true, engineCapacity: '1490 cc Hybrid', seatingCapacity: 5,
    createdAt: new Date('2024-02-18'), updatedAt: new Date('2024-02-18'),
  },
  {
    id: '25', brand: 'Honda', model: 'Elevate', year: 2024, price: 1650000,
    mileage: '15.3 kmpl', fuelType: 'Petrol', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Meteoroid Grey', owners: 1, location: 'Pune',
    images: img('suv', 4),
    features: ['Honda Sensing ADAS', 'Sunroof', 'Wireless AA/CarPlay', 'Ventilated Seats'],
    description: 'Honda Elevate ZX CVT with Level 2 ADAS. Brand new vehicle.',
    dealerId: 'd1', dealerName: 'Premium Motors', registrationYear: 2024,
    insuranceValidity: 'Mar 2027', kmDriven: 2800, rating: 4.6,
    isFeatured: true, isNew: true, engineCapacity: '1498 cc', seatingCapacity: 5,
    createdAt: new Date('2024-02-22'), updatedAt: new Date('2024-02-22'),
  },
  {
    id: '26', brand: 'Mahindra', model: 'Scorpio N', year: 2023, price: 1980000,
    mileage: '13.7 kmpl', fuelType: 'Diesel', transmission: 'Manual',
    bodyType: 'SUV', color: 'Deep Forest', owners: 1, location: 'Hyderabad',
    images: img('suv', 0),
    features: ['4WD', 'ADAS', 'AdrenoX Connected', 'Sony Music', 'Meridian Sound'],
    description: 'Mahindra Scorpio N Z8L diesel 4WD. Fully loaded with all features.',
    dealerId: 'd4', dealerName: 'Luxury Car Point', registrationYear: 2023,
    insuranceValidity: 'Nov 2026', kmDriven: 13000, rating: 4.7,
    isFeatured: true, isNew: false, engineCapacity: '2184 cc', seatingCapacity: 7,
    createdAt: new Date('2024-01-26'), updatedAt: new Date('2024-01-26'),
  },
  {
    id: '27', brand: 'Tata', model: 'Harrier', year: 2023, price: 2050000,
    mileage: '14.6 kmpl', fuelType: 'Diesel', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Orcus White', owners: 1, location: 'Surat',
    images: img('suv', 1),
    features: ['JBL Sound System', 'ADAS', 'Panoramic Sunroof', '9-Speaker Audio'],
    description: 'Tata Harrier XZA+ top variant diesel AT. Loaded luxury SUV.',
    dealerId: 'd3', dealerName: 'EV Motors Hub', registrationYear: 2023,
    insuranceValidity: 'Aug 2026', kmDriven: 15000, rating: 4.5,
    isFeatured: false, isNew: false, engineCapacity: '1956 cc', seatingCapacity: 5,
    createdAt: new Date('2024-01-19'), updatedAt: new Date('2024-01-19'),
  },
  {
    id: '28', brand: 'Kia', model: 'Carens', year: 2023, price: 1730000,
    mileage: '16.5 kmpl', fuelType: 'Diesel', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Glacier White', owners: 1, location: 'Kolkata',
    images: img('suv', 2),
    features: ['7-Seater', '10.25" Screen', 'Bose 8-Speaker', 'Electric Sunroof', 'ADAS'],
    description: 'Kia Carens Luxury Plus 6AT. Best-in-class 6-seat MPV.',
    dealerId: 'd2', dealerName: 'City Auto Sales', registrationYear: 2023,
    insuranceValidity: 'Oct 2026', kmDriven: 9800, rating: 4.6,
    isFeatured: false, isNew: false, engineCapacity: '1493 cc', seatingCapacity: 6,
    createdAt: new Date('2024-02-06'), updatedAt: new Date('2024-02-06'),
  },
  {
    id: '29', brand: 'Toyota', model: 'Innova Crysta', year: 2022, price: 2250000,
    mileage: '14.29 kmpl', fuelType: 'Diesel', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Super White', owners: 1, location: 'Delhi',
    images: img('suv', 3),
    features: ['7-Seater', 'Ventilated Seats', 'JBL Sound', 'Connected Car', '360 View'],
    description: 'Toyota Innova Crysta ZX AT diesel. Premium MPV in showroom condition.',
    dealerId: 'd4', dealerName: 'Luxury Car Point', registrationYear: 2022,
    insuranceValidity: 'Dec 2025', kmDriven: 26000, rating: 4.7,
    isFeatured: true, isNew: false, engineCapacity: '2393 cc', seatingCapacity: 7,
    createdAt: new Date('2024-01-14'), updatedAt: new Date('2024-01-14'),
  },
  {
    id: '30', brand: 'Volkswagen', model: 'Taigun', year: 2023, price: 1760000,
    mileage: '17.6 kmpl', fuelType: 'Petrol', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Candy White', owners: 1, location: 'Ahmedabad',
    images: img('suv', 4),
    features: ['10" Touchscreen', 'DSG Gearbox', 'Traction Control', 'LED Matrix Headlamps'],
    description: 'Volkswagen Taigun GT Plus DSG. German engineering at its best.',
    dealerId: 'd5', dealerName: 'Euro Cars Gallery', registrationYear: 2023,
    insuranceValidity: 'Jul 2026', kmDriven: 7400, rating: 4.5,
    isFeatured: false, isNew: false, engineCapacity: '1498 cc', seatingCapacity: 5,
    createdAt: new Date('2024-02-09'), updatedAt: new Date('2024-02-09'),
  },
  {
    id: '31', brand: 'Skoda', model: 'Slavia', year: 2023, price: 1620000,
    mileage: '18.2 kmpl', fuelType: 'Petrol', transmission: 'Automatic',
    bodyType: 'Sedan', color: 'Carbon Steel', owners: 1, location: 'Bangalore',
    images: img('sedan', 2),
    features: ['Wireless CarPlay', 'Ventilated Seats', 'Electric Sunroof', 'TPMS'],
    description: 'Skoda Slavia Style 1.5 TSI DSG. The best sedan for enthusiasts.',
    dealerId: 'd5', dealerName: 'Euro Cars Gallery', registrationYear: 2023,
    insuranceValidity: 'Apr 2026', kmDriven: 8900, rating: 4.6,
    isFeatured: false, isNew: false, engineCapacity: '1498 cc', seatingCapacity: 5,
    createdAt: new Date('2024-02-11'), updatedAt: new Date('2024-02-11'),
  },
  {
    id: '32', brand: 'Hyundai', model: 'Alcazar', year: 2023, price: 1950000,
    mileage: '17.5 kmpl', fuelType: 'Petrol', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Typhoon Silver', owners: 1, location: 'Mumbai',
    images: img('suv', 0),
    features: ['6-Seater Captain Seats', 'Dual Sunroof', 'BOSE Sound', 'ADAS Level 2'],
    description: 'Hyundai Alcazar Signature petrol AT 6-seater. Luxury family SUV.',
    dealerId: 'd2', dealerName: 'City Auto Sales', registrationYear: 2023,
    insuranceValidity: 'Sep 2026', kmDriven: 6700, rating: 4.5,
    isFeatured: false, isNew: false, engineCapacity: '1999 cc', seatingCapacity: 6,
    createdAt: new Date('2024-01-23'), updatedAt: new Date('2024-01-23'),
  },
  {
    id: '33', brand: 'Jeep', model: 'Compass', year: 2023, price: 2550000,
    mileage: '15.3 kmpl', fuelType: 'Diesel', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Techno Green', owners: 1, location: 'Pune',
    images: img('suv', 1),
    features: ['4x4 AWD', 'Meridian Sound', 'ADAS', 'Ventilated Seats', 'Panoramic Roof'],
    description: 'Jeep Compass Model S diesel AT. Built to go anywhere.',
    dealerId: 'd4', dealerName: 'Luxury Car Point', registrationYear: 2023,
    insuranceValidity: 'Feb 2026', kmDriven: 10500, rating: 4.6,
    isFeatured: true, isNew: false, engineCapacity: '1956 cc', seatingCapacity: 5,
    createdAt: new Date('2024-01-27'), updatedAt: new Date('2024-01-27'),
  },
  {
    id: '34', brand: 'Toyota', model: 'Innova Hycross', year: 2024, price: 2480000,
    mileage: '21.1 kmpl', fuelType: 'Hybrid', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Platinum White', owners: 1, location: 'Delhi',
    images: img('suv', 2),
    features: ['Strong Hybrid', 'ADAS', 'Otto Mode', 'JBL Sound', 'PM2.5 Air Filter'],
    description: 'Toyota Innova HyCross ZX+ Hybrid AT. The future of MPVs.',
    dealerId: 'd4', dealerName: 'Luxury Car Point', registrationYear: 2024,
    insuranceValidity: 'Jan 2027', kmDriven: 4500, rating: 4.9,
    isFeatured: true, isNew: true, engineCapacity: '1987 cc Hybrid', seatingCapacity: 7,
    createdAt: new Date('2024-02-19'), updatedAt: new Date('2024-02-19'),
  },
  {
    id: '35', brand: 'Mahindra', model: 'Thar Roxx', year: 2024, price: 1599000,
    mileage: '15.2 kmpl', fuelType: 'Diesel', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Everest White', owners: 1, location: 'Hyderabad',
    images: img('suv', 3),
    features: ['4WD', 'ADAS', 'Sky-Control Roof', 'Sony Sound', 'L9 Controller'],
    description: 'All-new Mahindra Thar Roxx MX5 diesel AT. 5-door Thar variant.',
    dealerId: 'd4', dealerName: 'Luxury Car Point', registrationYear: 2024,
    insuranceValidity: 'Dec 2026', kmDriven: 3000, rating: 4.8,
    isFeatured: true, isNew: true, engineCapacity: '2184 cc', seatingCapacity: 5,
    createdAt: new Date('2024-02-25'), updatedAt: new Date('2024-02-25'),
  },

  // ── 36-43: Premium & Luxury ₹40L–₹80L ────────────────────────────────────
  {
    id: '36', brand: 'BMW', model: '3 Series', year: 2023, price: 5200000,
    mileage: '14.6 kmpl', fuelType: 'Petrol', transmission: 'Automatic',
    bodyType: 'Sedan', color: 'Alpine White', owners: 1, location: 'Mumbai',
    images: img('luxury', 0),
    features: ['BMW Live Cockpit Pro', 'Harman Kardon Sound', 'Parking Assist', 'Wireless AA'],
    description: 'BMW 330i M Sport. The ultimate driving machine in perfect condition.',
    dealerId: 'd4', dealerName: 'Luxury Car Point', registrationYear: 2023,
    insuranceValidity: 'Feb 2026', kmDriven: 15000, rating: 4.8,
    isFeatured: true, isNew: false, engineCapacity: '1998 cc', seatingCapacity: 5,
    createdAt: new Date('2024-01-16'), updatedAt: new Date('2024-01-16'),
  },
  {
    id: '37', brand: 'Audi', model: 'Q3', year: 2023, price: 5100000,
    mileage: '13.4 kmpl', fuelType: 'Petrol', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Monsoon Grey', owners: 1, location: 'Delhi',
    images: img('luxury', 1),
    features: ['Virtual Cockpit', 'Matrix LED', 'Adaptive Cruise', 'Bang & Olufsen Sound'],
    description: 'Audi Q3 45 TFSI quattro. Perfect blend of luxury and performance.',
    dealerId: 'd5', dealerName: 'Euro Cars Gallery', registrationYear: 2023,
    insuranceValidity: 'Apr 2026', kmDriven: 11000, rating: 4.7,
    isFeatured: false, isNew: false, engineCapacity: '1984 cc', seatingCapacity: 5,
    createdAt: new Date('2024-02-04'), updatedAt: new Date('2024-02-04'),
  },
  {
    id: '38', brand: 'Mercedes-Benz', model: 'C-Class', year: 2022, price: 5800000,
    mileage: '12.9 kmpl', fuelType: 'Petrol', transmission: 'Automatic',
    bodyType: 'Sedan', color: 'Obsidian Black', owners: 1, location: 'Bangalore',
    images: img('luxury', 2),
    features: ['MBUX Hyperscreen', 'Burmester 3D Sound', 'Air Body Control', 'ADAS Level 2'],
    description: 'Mercedes-Benz C 220d AMG Line. Pinnacle of luxury sedans.',
    dealerId: 'd4', dealerName: 'Luxury Car Point', registrationYear: 2022,
    insuranceValidity: 'Jan 2026', kmDriven: 18000, rating: 4.9,
    isFeatured: true, isNew: false, engineCapacity: '1993 cc', seatingCapacity: 5,
    createdAt: new Date('2024-01-21'), updatedAt: new Date('2024-01-21'),
  },
  {
    id: '39', brand: 'BMW', model: '5 Series', year: 2022, price: 7200000,
    mileage: '13.2 kmpl', fuelType: 'Petrol', transmission: 'Automatic',
    bodyType: 'Sedan', color: 'Black Sapphire', owners: 1, location: 'Mumbai',
    images: img('luxury', 0),
    features: ['Driving Assistant Pro', 'Bowers & Wilkins Sound', 'Night Vision', 'Massaging Seats'],
    description: 'BMW 530i M Sport. Executive sedan with exceptional tech.',
    dealerId: 'd4', dealerName: 'Luxury Car Point', registrationYear: 2022,
    insuranceValidity: 'Oct 2025', kmDriven: 22000, rating: 4.8,
    isFeatured: false, isNew: false, engineCapacity: '1998 cc', seatingCapacity: 5,
    createdAt: new Date('2024-01-11'), updatedAt: new Date('2024-01-11'),
  },
  {
    id: '40', brand: 'Audi', model: 'A4', year: 2023, price: 5600000,
    mileage: '12.7 kmpl', fuelType: 'Petrol', transmission: 'Automatic',
    bodyType: 'Sedan', color: 'Floret Silver', owners: 1, location: 'Delhi',
    images: img('luxury', 1),
    features: ['Audi Virtual Cockpit Plus', 'Bang & Olufsen Premium Sound', 'MMI Navigation'],
    description: 'Audi A4 40 TFSI Technology. A legend reimagined.',
    dealerId: 'd5', dealerName: 'Euro Cars Gallery', registrationYear: 2023,
    insuranceValidity: 'Jun 2026', kmDriven: 8500, rating: 4.7,
    isFeatured: false, isNew: false, engineCapacity: '1984 cc', seatingCapacity: 5,
    createdAt: new Date('2024-02-13'), updatedAt: new Date('2024-02-13'),
  },
  {
    id: '41', brand: 'Mercedes-Benz', model: 'GLC', year: 2023, price: 8500000,
    mileage: '11.2 kmpl', fuelType: 'Petrol', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Diamond White', owners: 1, location: 'Chennai',
    images: img('luxury', 2),
    features: ['AMG Line', 'MBUX Infotainment', 'Panoramic Roof', 'Air Suspension', 'ADAS Pro'],
    description: 'Mercedes-Benz GLC 300 4MATIC AMG Line. Luxury at every corner.',
    dealerId: 'd4', dealerName: 'Luxury Car Point', registrationYear: 2023,
    insuranceValidity: 'Jul 2026', kmDriven: 7000, rating: 4.9,
    isFeatured: true, isNew: false, engineCapacity: '1999 cc Turbo', seatingCapacity: 5,
    createdAt: new Date('2024-02-01'), updatedAt: new Date('2024-02-01'),
  },
  {
    id: '42', brand: 'Jeep', model: 'Meridian', year: 2023, price: 3800000,
    mileage: '14.8 kmpl', fuelType: 'Diesel', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Velvet Red', owners: 1, location: 'Pune',
    images: img('suv', 4),
    features: ['7-Seater', 'Meridian Sound', 'Quadra-Trac AWD', 'Panoramic Sunroof', 'ADAS'],
    description: 'Jeep Meridian X diesel AT. The flagship Jeep for Indian roads.',
    dealerId: 'd4', dealerName: 'Luxury Car Point', registrationYear: 2023,
    insuranceValidity: 'Mar 2026', kmDriven: 9200, rating: 4.6,
    isFeatured: false, isNew: false, engineCapacity: '1956 cc', seatingCapacity: 7,
    createdAt: new Date('2024-01-29'), updatedAt: new Date('2024-01-29'),
  },
  {
    id: '43', brand: 'Volvo', model: 'XC40', year: 2023, price: 5199000,
    mileage: '14.1 kmpl', fuelType: 'Petrol', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Cloud Blue', owners: 1, location: 'Mumbai',
    images: img('luxury', 1),
    features: ['Google Built-In', 'Harman Kardon Sound', 'AWD', 'Pilot Assist', 'Air Cleaner'],
    description: 'Volvo XC40 B4 AWD. Scandinavian safety meets modern luxury.',
    dealerId: 'd4', dealerName: 'Luxury Car Point', registrationYear: 2023,
    insuranceValidity: 'Aug 2026', kmDriven: 12000, rating: 4.8,
    isFeatured: false, isNew: false, engineCapacity: '1969 cc', seatingCapacity: 5,
    createdAt: new Date('2024-02-14'), updatedAt: new Date('2024-02-14'),
  },

  // ── 44-50: Electric vehicles ──────────────────────────────────────────────
  {
    id: '44', brand: 'MG', model: 'ZS EV', year: 2024, price: 2688000,
    mileage: '461 km/charge', fuelType: 'Electric', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Dover White', owners: 1, location: 'Bangalore',
    images: img('electric', 0),
    features: ['50 kWh Battery', 'DC Fast Charge', 'i-SMART Connected', 'Panoramic Glass'],
    description: 'MG ZS EV Excite Pro. 461 km range with premium electric SUV experience.',
    dealerId: 'd3', dealerName: 'EV Motors Hub', registrationYear: 2024,
    insuranceValidity: 'Feb 2027', kmDriven: 2800, rating: 4.5,
    isFeatured: true, isNew: true, engineCapacity: '50 kWh Motor', seatingCapacity: 5,
    createdAt: new Date('2024-02-23'), updatedAt: new Date('2024-02-23'),
  },
  {
    id: '45', brand: 'Tata', model: 'Tigor EV', year: 2023, price: 1450000,
    mileage: '306 km/charge', fuelType: 'Electric', transmission: 'Automatic',
    bodyType: 'Sedan', color: 'Midnight Plum', owners: 1, location: 'Delhi',
    images: img('electric', 1),
    features: ['30.2 kWh Battery', 'Fast Charge', 'Connected iRA', 'Electric Parking Brake'],
    description: 'Tata Tigor EV XZ+ Long Range. Affordable and practical electric sedan.',
    dealerId: 'd3', dealerName: 'EV Motors Hub', registrationYear: 2023,
    insuranceValidity: 'Nov 2026', kmDriven: 8500, rating: 4.3,
    isFeatured: false, isNew: false, engineCapacity: '30.2 kWh Motor', seatingCapacity: 5,
    createdAt: new Date('2024-01-24'), updatedAt: new Date('2024-01-24'),
  },
  {
    id: '46', brand: 'Hyundai', model: 'Kona Electric', year: 2022, price: 2390000,
    mileage: '452 km/charge', fuelType: 'Electric', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Aqua Turquoise', owners: 1, location: 'Pune',
    images: img('electric', 2),
    features: ['39.2 kWh Battery', 'V2L Capability', 'ADAS', 'Wireless Charging', 'Sunroof'],
    description: 'Hyundai Kona Electric. The first premium electric SUV in India.',
    dealerId: 'd3', dealerName: 'EV Motors Hub', registrationYear: 2022,
    insuranceValidity: 'Oct 2025', kmDriven: 18000, rating: 4.5,
    isFeatured: false, isNew: false, engineCapacity: '39.2 kWh Motor', seatingCapacity: 5,
    createdAt: new Date('2024-01-09'), updatedAt: new Date('2024-01-09'),
  },
  {
    id: '47', brand: 'Kia', model: 'EV6', year: 2023, price: 6095000,
    mileage: '528 km/charge', fuelType: 'Electric', transmission: 'Automatic',
    bodyType: 'Coupe', color: 'Aurora Black', owners: 1, location: 'Mumbai',
    images: img('electric', 0),
    features: ['77.4 kWh Battery', 'AWD', 'V2L/V2V', 'Augmented Reality HUD', '0-100 in 3.5s'],
    description: 'Kia EV6 GT Line AWD. Performance EV redefines the category.',
    dealerId: 'd4', dealerName: 'Luxury Car Point', registrationYear: 2023,
    insuranceValidity: 'Apr 2026', kmDriven: 6500, rating: 4.9,
    isFeatured: true, isNew: false, engineCapacity: '77.4 kWh Dual Motor', seatingCapacity: 5,
    createdAt: new Date('2024-02-16'), updatedAt: new Date('2024-02-16'),
  },
  {
    id: '48', brand: 'Volvo', model: 'XC40 Recharge', year: 2023, price: 5699000,
    mileage: '418 km/charge', fuelType: 'Electric', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Crystal White', owners: 1, location: 'Delhi',
    images: img('luxury', 2),
    features: ['78 kWh Battery', 'AWD', 'Google Built-In', 'Pilot Assist', 'Harman Kardon'],
    description: 'Volvo XC40 Recharge. Pure electric with Swedish safety design.',
    dealerId: 'd4', dealerName: 'Luxury Car Point', registrationYear: 2023,
    insuranceValidity: 'Jun 2026', kmDriven: 9000, rating: 4.8,
    isFeatured: false, isNew: false, engineCapacity: '78 kWh Dual Motor', seatingCapacity: 5,
    createdAt: new Date('2024-02-17'), updatedAt: new Date('2024-02-17'),
  },
  {
    id: '49', brand: 'BYD', model: 'Atto 3', year: 2024, price: 3490000,
    mileage: '521 km/charge', fuelType: 'Electric', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Ski White', owners: 1, location: 'Bangalore',
    images: img('electric', 1),
    features: ['60.48 kWh Blade Battery', 'NFC Card', 'AR Instrument Cluster', 'V2L'],
    description: 'BYD Atto 3 Excellence. 521 km range with Blade Battery safety.',
    dealerId: 'd3', dealerName: 'EV Motors Hub', registrationYear: 2024,
    insuranceValidity: 'Jan 2027', kmDriven: 1500, rating: 4.6,
    isFeatured: true, isNew: true, engineCapacity: '60.48 kWh Motor', seatingCapacity: 5,
    createdAt: new Date('2024-02-24'), updatedAt: new Date('2024-02-24'),
  },
  {
    id: '50', brand: 'Tata', model: 'Nexon EV Max', year: 2024, price: 2195000,
    mileage: '437 km/charge', fuelType: 'Electric', transmission: 'Automatic',
    bodyType: 'SUV', color: 'Pristine White', owners: 1, location: 'Chennai',
    images: img('electric', 2),
    features: ['40.5 kWh Battery', 'CCS2 Fast Charge', 'ADAS', 'Wireless AA', 'Ventilated Seats'],
    description: 'Tata Nexon EV Max. India\'s best-selling electric SUV with 437 km range.',
    dealerId: 'd3', dealerName: 'EV Motors Hub', registrationYear: 2024,
    insuranceValidity: 'Jan 2027', kmDriven: 4200, rating: 4.8,
    isFeatured: true, isNew: true, engineCapacity: '40.5 kWh Motor', seatingCapacity: 5,
    createdAt: new Date('2024-02-26'), updatedAt: new Date('2024-02-26'),
  },
];
